### ISSUE TITLE
Error when execute the flow graph

### ISSUE THREAD

**Issue by nazmibojan** [trendmicro/ais#11]
Hi,

I already installed gnu radio and build ais-master without problem. But when I executed the graph, I got this error:

Traceback (most recent call last):
  File "/home/nazmi/Documents/Pernika/Code/ais-master/top_block.py", line 29, in <module>
    import AISTX
  File "/usr/local/lib/python2.7/dist-packages/AISTX/__init__.py", line 45, in <module>
    from AISTX_swig import *
  File "/usr/local/lib/python2.7/dist-packages/AISTX/AISTX_swig.py", line 28, in <module>
    _AISTX_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/AISTX/AISTX_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_AISTX_swig', fp, pathname, description)
ImportError: libgnuradio-AISTX.so: cannot open shared object file: No such file or directory

I'm newbie in GNU radio, and hope the solution from you.
Thanks.

Nazmi

**Comment by nazmibojan** [comment]
Sorry, I forgot to hit 'sudo ldconfig' after change /etc/gnuradio/conf.d/grc.conf file.
Thanks.
